spring:
  application.name: "API"
  sql.init.mode: always
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: "create"
    defer-datasource-initialization: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/workshop_i2"
    username: "postgres"
    password: "*lqR0&>>sQ$42>j3"
