spring:
  application.name: "API"
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: "create-drop"
  datasource:
    url: "jdbc:postgresql://localhost:5432/workshop_i2"
    username: "postgres"
    password: "*lqR0&>>sQ$42>j3"
